[project]
name = "planet"
version = "0.1.0"
description = "PlaNet: A Deep Planning Network for Reinforcement Learning"
requires-python = ">=3.9"
dependencies = [
    "gym==0.23.1",
    "gymnasium>=1.1.1",
    "imageio",
    "numpy<2",
    "opencv-python",
    "plotly",
    "pygame",
    "torch",
    "torchvision",
    "tqdm",
]

[dependency-groups]
dev = []
